{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "7.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.3.0.aar",
          "url": "databinding-runtime-7.3.0.aar",
          "size": 61975,
          "sha512": "61d40ee0eebb525f1d7f9fb7264085d9066a4a3cff1e41ef085f47224544c189702e8520dec7aa1bdf11524c26a02ce2bcfef89caa9755977e8c3b50065c18af",
          "sha256": "6afc8bc945a0d148b693aed30230e70d4503aa564f7ec1d31148f99685739193",
          "sha1": "603d1b5537d458e78b448446d6a7cecf0f8360e8",
          "md5": "ed312e18ae7b06dfc148b43aca769f74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.3.0.aar",
          "url": "databinding-runtime-7.3.0.aar",
          "size": 61975,
          "sha512": "61d40ee0eebb525f1d7f9fb7264085d9066a4a3cff1e41ef085f47224544c189702e8520dec7aa1bdf11524c26a02ce2bcfef89caa9755977e8c3b50065c18af",
          "sha256": "6afc8bc945a0d148b693aed30230e70d4503aa564f7ec1d31148f99685739193",
          "sha1": "603d1b5537d458e78b448446d6a7cecf0f8360e8",
          "md5": "ed312e18ae7b06dfc148b43aca769f74"
        }
      ]
    }
  ]
}
