{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt",
    "module": "coil",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h6yy3iqahzcetfp7sqxva2ykxq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "coil-1.1.1.aar",
          "url": "coil-1.1.1.aar",
          "size": 16011,
          "sha512": "015c64fad186368fe71422a7509a483dab52ead364911792c5a4cbbc72fe37263cc2f32e638764b7193d57d5d4d0c8ae10ea1b37e25442e1418afe0d8855e6b9",
          "sha256": "5e701c3182aad4ede8df537d816c3b70858734010be5a3d6ca4cffef5043fc5e",
          "sha1": "f87a74d33a65734390b398f6975627b23e6df22f",
          "md5": "e844f5c80de752476e1e233c3c20325d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "coil-1.1.1.aar",
          "url": "coil-1.1.1.aar",
          "size": 16011,
          "sha512": "015c64fad186368fe71422a7509a483dab52ead364911792c5a4cbbc72fe37263cc2f32e638764b7193d57d5d4d0c8ae10ea1b37e25442e1418afe0d8855e6b9",
          "sha256": "5e701c3182aad4ede8df537d816c3b70858734010be5a3d6ca4cffef5043fc5e",
          "sha1": "f87a74d33a65734390b398f6975627b23e6df22f",
          "md5": "e844f5c80de752476e1e233c3c20325d"
        }
      ]
    }
  ]
}
